# Generated by Django 4.2.7 on 2024-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalphoto',
            name='image',
            field=models.ImageField(upload_to='principal_photo/%Y%m'),
        ),
    ]
