# Generated by Django 4.2.7 on 2024-01-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_principalphoto_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='ArtProjects',
        ),
    ]
