# Generated by Django 4.2.7 on 2024-01-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_projects_artprojects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principalphoto',
            options={'verbose_name': 'Photo'},
        ),
        migrations.AddField(
            model_name='principalphoto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
