# Generated by Django 4.2.7 on 2024-01-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_principalphoto_options_principalphoto_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrincipalPhoto',
        ),
    ]
