# Generated by Django 4.2.7 on 2024-01-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_mainphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainphoto',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
