# Generated by Django 4.2.7 on 2024-01-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_photo_delete_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coding_photo/%Y/%m')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
