# Generated by Django 4.2.7 on 2024-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_codeprojects_alter_artprojects_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeprojects',
            name='image',
            field=models.ImageField(unique=True, upload_to='coding_photo/%Y/%m'),
        ),
    ]
