# Generated by Django 4.2.7 on 2024-01-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_codeprojects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='art/main_photo/%Y/%m')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Art photo',
            },
        ),
        migrations.AlterField(
            model_name='artprojects',
            name='image',
            field=models.ImageField(unique=True, upload_to='art/projects/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='codeprojects',
            name='image',
            field=models.ImageField(unique=True, upload_to='coding/projects/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='codingphoto',
            name='image',
            field=models.ImageField(upload_to='coding/main_photo/%Y/%m'),
        ),
    ]
