# Generated by Django 4.2.7 on 2024-02-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_artphoto_alter_artprojects_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artprojects',
            options={'ordering': ['order'], 'verbose_name': 'Draw', 'verbose_name_plural': 'Draws'},
        ),
        migrations.AddField(
            model_name='artprojects',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
