# Generated by Django 4.2.7 on 2024-02-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_artprojects_options_artprojects_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artprojects',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
