# Generated by Django 4.2.7 on 2024-02-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_artprojects_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artprojects',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
