# Generated by Django 4.2.7 on 2024-02-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_artprojects_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artprojects',
            options={'verbose_name': 'Draw', 'verbose_name_plural': 'Draws'},
        ),
        migrations.RemoveField(
            model_name='artprojects',
            name='order',
        ),
    ]
